"""empty message

Revision ID: faa17bb6520a
Revises: 
Create Date: 2020-03-23 17:49:45.544313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa17bb6520a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gastro_classes',
    sa.Column('gastro_classes_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('gastro_classes_id')
    )
    op.create_table('resources',
    sa.Column('resource_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_table('zoon_places',
    sa.Column('zoon_place_id', sa.BigInteger(), nullable=False),
    sa.Column('zoon_place_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('zoon_place_id')
    )
    op.create_table('crawling_info',
    sa.Column('crawling_info_id', sa.BigInteger(), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('crawl_start_time', sa.DateTime(), nullable=True),
    sa.Column('crawl_end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], ),
    sa.PrimaryKeyConstraint('crawling_info_id')
    )
    op.create_table('zoon_gastros',
    sa.Column('zoon_gastro_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('synonym_id', sa.BigInteger(), nullable=True),
    sa.Column('gastro_classes_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['gastro_classes_id'], ['gastro_classes.gastro_classes_id'], ),
    sa.ForeignKeyConstraint(['synonym_id'], ['zoon_gastros.zoon_gastro_id'], ),
    sa.PrimaryKeyConstraint('zoon_gastro_id')
    )
    op.create_table('responses',
    sa.Column('response_id', sa.BigInteger(), nullable=False),
    sa.Column('response_time', sa.DateTime(), nullable=True),
    sa.Column('query_location', sa.String(), nullable=True),
    sa.Column('query_gastro', sa.String(), nullable=True),
    sa.Column('zoon_place_id', sa.BigInteger(), nullable=True),
    sa.Column('zoon_gastro_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['zoon_gastro_id'], ['zoon_gastros.zoon_gastro_id'], ),
    sa.ForeignKeyConstraint(['zoon_place_id'], ['zoon_places.zoon_place_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_table('zoon_menues',
    sa.Column('zoon_menu_id', sa.BigInteger(), nullable=False),
    sa.Column('zoon_place_id', sa.BigInteger(), nullable=True),
    sa.Column('zoon_gastro_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['zoon_gastro_id'], ['zoon_gastros.zoon_gastro_id'], ),
    sa.ForeignKeyConstraint(['zoon_place_id'], ['zoon_places.zoon_place_id'], ),
    sa.PrimaryKeyConstraint('zoon_menu_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zoon_menues')
    op.drop_table('responses')
    op.drop_table('zoon_gastros')
    op.drop_table('crawling_info')
    op.drop_table('zoon_places')
    op.drop_table('resources')
    op.drop_table('gastro_classes')
    # ### end Alembic commands ###
